spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: user
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  redis:
    port: 6379
    host: localhost